# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_Capture = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Capture.setGeometry(QtCore.QRect(400, 340, 160, 60))
        self.Button_Capture.setObjectName("Button_Capture")
        self.Button_OpenCamera = QtWidgets.QPushButton(self.centralwidget)
        self.Button_OpenCamera.setGeometry(QtCore.QRect(160, 340, 160, 60))
        self.Button_OpenCamera.setObjectName("Button_OpenCamera")
        self.label_Camera = QtWidgets.QLabel(self.centralwidget)
        self.label_Camera.setGeometry(QtCore.QRect(20, 0, 480, 320))
        self.label_Camera.setObjectName("label_Camera")
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_Capture = QtWidgets.QLabel(self.centralwidget)
        self.label_Capture.setGeometry(QtCore.QRect(510, 64, 200, 200))
        self.label_Capture.setObjectName("label_Capture")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 5))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Button_OpenCamera.clicked.connect(MainWindow.Button_OpenCamera_Clicked)
        self.Button_Capture.clicked.connect(MainWindow.Button_Capture_Clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_Capture.setText(_translate("MainWindow", "截取图片"))
        self.Button_OpenCamera.setText(_translate("MainWindow", "打开摄像头"))
        self.label_Camera.setText(_translate("MainWindow", "实时显示"))
        self.label_Capture.setText(_translate("MainWindow", "photo"))
